Trigger workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -60,7 +60,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Install GTK dependencies
-        run: choco install gtk-runtime
+        run: choco install gtk3
         shell: cmd
 
       - name: Check for existing Python installation
@@ -90,19 +90,15 @@ jobs:
           C:\tools\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-cairo mingw-w64-x86_64-pango mingw-w64-x86_64-gtk3"
         shell: cmd
 
-      - name: Set GTK environment variables
+      - name: Debug GTK installation
         run: |
-          echo "C:\\tools\\gtk3\\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
+          Get-ChildItem -Path "C:\\tools"
+          Get-ChildItem -Path "C:\\tools\\msys64\\mingw64\\bin"
         shell: powershell
 
       - name: Verify GTK installation
         run: |
-          if (-Not (Test-Path -Path "C:\\tools\\gtk3\\bin\\libcairo-2.dll")) { Write-Error "GTK installation failed"; exit 1 } else { Write-Output "GTK installation verified" }
-        shell: powershell
-
-      - name: Debug GTK installation
-        run: |
-          Get-ChildItem -Path "C:\\tools\\gtk3\\bin"
+          if (-Not (Test-Path -Path "C:\\tools\\msys64\\mingw64\\bin\\libcairo-2.dll")) { Write-Error "GTK installation failed"; exit 1 } else { Write-Output "GTK installation verified" }
         shell: powershell
 
       - name: Display PATH variable
