Trigger workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -92,17 +92,17 @@ jobs:
 
       - name: Set GTK environment variables
         run: |
-          echo "C:\\Program Files (x86)\\GTK2-Runtime Win64\\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
+          echo "C:\\tools\\gtk3\\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
         shell: powershell
 
       - name: Verify GTK installation
         run: |
-          if (-Not (Test-Path -Path "C:\\Program Files (x86)\\GTK2-Runtime Win64\\bin\\libcairo-2.dll")) { Write-Error "GTK installation failed"; exit 1 } else { Write-Output "GTK installation verified" }
+          if (-Not (Test-Path -Path "C:\\tools\\gtk3\\bin\\libcairo-2.dll")) { Write-Error "GTK installation failed"; exit 1 } else { Write-Output "GTK installation verified" }
         shell: powershell
 
       - name: Debug GTK installation
         run: |
-          Get-ChildItem -Path "C:\\Program Files (x86)\\GTK2-Runtime Win64\\bin"
+          Get-ChildItem -Path "C:\\tools\\gtk3\\bin"
         shell: powershell
 
       - name: Display PATH variable
